### ISSUE TITLE
Verbandbuch neue Features (UI)

### ISSUE THREAD

**Issue by odenwaelder** [8devs/Verbandbuch-App#1]
- [x] PDF Exporte von einzelnen Niederlassungen und Abteilungen
- [x] Löschen von Beinahunfällen und unsicheren Handlungen
- [x] Graph im Dashboard zum Anzeigen der Entwicklung der Einträge
- [x] Text und Design für E-Mail bei neuen Einträgen
- [x] E-Mail subscribe in Profil
- [x] PDF Design für einzelne Einträge

**Comment by odenwaelder** [comment]
@JonasDeichelmann @pascalwenner @LukasPhilipp 

Wie am Mittwoch besprochen, habe ich die neuen Anforderungen an die Verbandbuch App konzeptioniert.

**Das gibt es neues im Web:** 

- Analyse Feature im Dashboard
- Einstellung der E-Mail Benachrichtigung im Profil
- Möglichkeit Beinahunfälle und unsichere Handlungen zu löschen
- PDF Export einzelner Einträge
- Zusätzlicher Filter bei Exportfunktion 

https://sebastian141242.invisionapp.com/overview/8devs-Webapp-ck8ipyr0l0z8g018hn1b07b10/screens/53621455?sortBy=1&sortOrder=1&viewLayout=2

**Das gibt es neues in den mobilen Apps:**

- Einstellung der E-Mail Benachrichtigung im Profil
- Möglichkeit Beinahunfälle und unsichere Handlungen zu löschen
- PDF Export einzelner Einträge

https://sebastian141242.invisionapp.com/overview/8devs-App-ck6nycmuj04n7019nih73msuz/screens/53621534?sortBy=1&sortOrder=1&viewLayout=2

**PDF Exporte und Mail Templates**

- Einzelner Export Verbandbuch
- Einzelner Export Beinahunfall
- Mail Template Neuer Verbandbuch Eintrag
- Mail Template Neuer Beinahunfall 

https://dracoon.team/node/26707928


Für Feedback in Invision am besten direkt im Web kommentieren. Für die Dateien in Dracoon am besten mir direkt in Slack schreiben.

**Comment by JonasDeichelmann** [comment]
@odenwaelder Habe in Invision Feedback Abgegeben, bitte schau dir das nochmal an.

Bei den PDF-Exporten sollte unbedingt noch stehen: "Dieser Ausdruck ist von VORNAME NACHNAME am 30.07.2021 um 16:34 mithilfe, der Verbandbuch-Software der 8devs GmbH erstellt worden. Diesen Eintrag finden Sie auch in digitaler Version in  der Verbandbuch-Software, erreichbar unter Verbandbuch.8devs.io oder im App- und PlayStore."

**Comment by JonasDeichelmann** [comment]
Das Ticket wird in To-Do verschoben, da hier noch Tätigkeiten notwendig sind.

**Comment by odenwaelder** [comment]
@JonasDeichelmann bin die Anmerkungen durchgegangen und habe Anpassungen vorgenommen: 

- Einzelne Einträge können nur in der Detailansicht gedownloadet und gelöscht werden
- In den mobilen Apps wurden die Download und löschen Buttons durch Icons neben der Überschrift ersetzt
- In den PDFs wurde der von dir vorgeschlagene Text eingesetzt
- Im Profil ist der Push-Nachrichten Toggle dazu gekommen (allerdings nur mobile, im Web fände ich das eher unpassend oder?)

**Comment by JonasDeichelmann** [comment]
✅ Approved
